-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 15:52:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinicaOdonto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinicaOdonto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinicaOdonto` DEFAULT CHARACTER SET utf8 ;
USE `clinicaOdonto` ;

-- -----------------------------------------------------
-- Table `clinicaOdonto`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`Paciente` (
  `RG` VARCHAR(9) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `nomeSocial` VARCHAR(45) NULL,
  `dataNasc` DATE NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `historico` VARCHAR(45) NULL,
  `sexo` CHAR(1) NOT NULL,
  PRIMARY KEY (`RG`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`EnderecoPaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`EnderecoPaciente` (
  `Paciente_RG` VARCHAR(9) NOT NULL,
  `CEP` VARCHAR(9) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  INDEX `fk_EnderecoPaciente_Paciente1_idx` (`Paciente_RG` ASC) VISIBLE,
  PRIMARY KEY (`Paciente_RG`),
  CONSTRAINT `fk_EnderecoPaciente_Paciente1`
    FOREIGN KEY (`Paciente_RG`)
    REFERENCES `clinicaOdonto`.`Paciente` (`RG`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`Profissional` (
  `CPF` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `registroProf` VARCHAR(45) NOT NULL,
  `especializacao` VARCHAR(45) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`EnderecoProfissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`EnderecoProfissional` (
  `Profissional_CPF` VARCHAR(15) NOT NULL,
  `CEP` VARCHAR(9) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`Profissional_CPF`),
  CONSTRAINT `fk_EnderecoProfissional_Profissional1`
    FOREIGN KEY (`Profissional_CPF`)
    REFERENCES `clinicaOdonto`.`Profissional` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`TelefonePaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`TelefonePaciente` (
  `idTelefonePaciente` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `Paciente_RG` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idTelefonePaciente`),
  INDEX `fk_TelefonePaciente_Paciente1_idx` (`Paciente_RG` ASC) VISIBLE,
  CONSTRAINT `fk_TelefonePaciente_Paciente1`
    FOREIGN KEY (`Paciente_RG`)
    REFERENCES `clinicaOdonto`.`Paciente` (`RG`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`Dentista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`Dentista` (
  `Profissional_CPF` VARCHAR(15) NOT NULL,
  `CRO` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Profissional_CPF`),
  UNIQUE INDEX `CRO_UNIQUE` (`CRO` ASC) VISIBLE,
  CONSTRAINT `fk_Dentista_Profissional1`
    FOREIGN KEY (`Profissional_CPF`)
    REFERENCES `clinicaOdonto`.`Profissional` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`Agendamento` (
  `idAgendamento` INT NOT NULL AUTO_INCREMENT,
  `estadoConsulta` VARCHAR(30) NOT NULL,
  `tipoProcedimento` VARCHAR(60) NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `Dentista_Profissional_CPF` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idAgendamento`),
  UNIQUE INDEX `idAgendamento_UNIQUE` (`idAgendamento` ASC) VISIBLE,
  INDEX `fk_Agendamento_Dentista1_idx` (`Dentista_Profissional_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Agendamento_Dentista1`
    FOREIGN KEY (`Dentista_Profissional_CPF`)
    REFERENCES `clinicaOdonto`.`Dentista` (`Profissional_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`ProcedimentoOdonto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`ProcedimentoOdonto` (
  `codigoProced` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(15) NOT NULL,
  `custo` DECIMAL(6,2) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`codigoProced`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`RegistroFatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`RegistroFatura` (
  `idRegistroFatura` INT NOT NULL AUTO_INCREMENT,
  `metodoPagamento` VARCHAR(30) NOT NULL,
  `planoSaude` VARCHAR(30) NULL,
  `procedimento` VARCHAR(60) NOT NULL,
  `custo` DECIMAL(6,2) NOT NULL,
  `Paciente_RG` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idRegistroFatura`),
  INDEX `fk_RegistroFatura_Paciente_idx` (`Paciente_RG` ASC) VISIBLE,
  CONSTRAINT `fk_RegistroFatura_Paciente`
    FOREIGN KEY (`Paciente_RG`)
    REFERENCES `clinicaOdonto`.`Paciente` (`RG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`SeguroSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`SeguroSaude` (
  `idSeguroSaude` INT auto_increment NOT NULL,
  `nomeSegurado` VARCHAR(45) NOT NULL,
  `apolice` VARCHAR(30) NOT NULL,
  `cobertura` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idSeguroSaude`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`TelefoneSeguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`TelefoneSeguradora` (
  `idTelefoneSeguradora` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `SeguroSaude_idSeguroSaude` INT NOT NULL,
  PRIMARY KEY (`idTelefoneSeguradora`),
  INDEX `fk_TelefoneSeguradora_SeguroSaude1_idx` (`SeguroSaude_idSeguroSaude` ASC) VISIBLE,
  CONSTRAINT `fk_TelefoneSeguradora_SeguroSaude1`
    FOREIGN KEY (`SeguroSaude_idSeguroSaude`)
    REFERENCES `clinicaOdonto`.`SeguroSaude` (`idSeguroSaude`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`EmailSeguradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`EmailSeguradora` (
  `idEmailSeguradora` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `SeguroSaude_idSeguroSaude` INT NOT NULL,
  PRIMARY KEY (`idEmailSeguradora`),
  INDEX `fk_EmailSeguradora_SeguroSaude1_idx` (`SeguroSaude_idSeguroSaude` ASC) VISIBLE,
  CONSTRAINT `fk_EmailSeguradora_SeguroSaude1`
    FOREIGN KEY (`SeguroSaude_idSeguroSaude`)
    REFERENCES `clinicaOdonto`.`SeguroSaude` (`idSeguroSaude`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`Gerente` (
  `Profissional_CPF` VARCHAR(15) NOT NULL,
  `comissao` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`Profissional_CPF`),
  CONSTRAINT `fk_Gerente_Profissional1`
    FOREIGN KEY (`Profissional_CPF`)
    REFERENCES `clinicaOdonto`.`Profissional` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`Balanco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`Balanco` (
  `idBalanco` INT NOT NULL AUTO_INCREMENT,
  `folhaPag` DECIMAL(7,2) NOT NULL,
  `compraEquip` DECIMAL(7,2) NOT NULL,
  `receita` DECIMAL(7,2) NOT NULL,
  `custoSuprimento` DECIMAL(7,2) NOT NULL,
  `custoOperacional` DECIMAL(6,2) NOT NULL,
  `Gerente_Profissional_CPF` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idBalanco`),
  INDEX `fk_Balanco_Gerente1_idx` (`Gerente_Profissional_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Balanco_Gerente1`
    FOREIGN KEY (`Gerente_Profissional_CPF`)
    REFERENCES `clinicaOdonto`.`Gerente` (`Profissional_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`Laboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`Laboratorio` (
  `CNPJ` varchar(18) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `historicoTrab` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `Gerente_Profissional_CPF` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CNPJ`),
  INDEX `fk_Laboratorio_Gerente1_idx` (`Gerente_Profissional_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Laboratorio_Gerente1`
    FOREIGN KEY (`Gerente_Profissional_CPF`)
    REFERENCES `clinicaOdonto`.`Gerente` (`Profissional_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`TelefoneLaboratorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`TelefoneLaboratorio` (
  `idTelefoneLaboratorio` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `Laboratorio_CNPJ` varchar(18) NOT NULL,
  PRIMARY KEY (`idTelefoneLaboratorio`),
  INDEX `fk_TelefoneLaboratorio_Laboratorio1_idx` (`Laboratorio_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_TelefoneLaboratorio_Laboratorio1`
    FOREIGN KEY (`Laboratorio_CNPJ`)
    REFERENCES `clinicaOdonto`.`Laboratorio` (`CNPJ`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`TelefoneProfissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`TelefoneProfissional` (
  `idTelefoneProfissional` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `Profissional_CPF` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTelefoneProfissional`),
  INDEX `fk_TelefoneProfissional_Profissional1_idx` (`Profissional_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_TelefoneProfissional_Profissional1`
    FOREIGN KEY (`Profissional_CPF`)
    REFERENCES `clinicaOdonto`.`Profissional` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`AgendamentoPacienteProced`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`AgendamentoPacienteProced` (
  `ProcedimentoOdonto_codigoProced` INT NOT NULL,
  `Agendamento_idAgendamento` INT NOT NULL,
  `Paciente_RG` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ProcedimentoOdonto_codigoProced`, `Agendamento_idAgendamento`, `Paciente_RG`),
  INDEX `fk_ProcedimentoOdonto_has_Agendamento_Agendamento1_idx` (`Agendamento_idAgendamento` ASC) VISIBLE,
  INDEX `fk_ProcedimentoOdonto_has_Agendamento_ProcedimentoOdonto1_idx` (`ProcedimentoOdonto_codigoProced` ASC) VISIBLE,
  INDEX `fk_ProcedimentoOdonto_has_Agendamento_Paciente1_idx` (`Paciente_RG` ASC) VISIBLE,
  CONSTRAINT `fk_ProcedimentoOdonto_has_Agendamento_ProcedimentoOdonto1`
    FOREIGN KEY (`ProcedimentoOdonto_codigoProced`)
    REFERENCES `clinicaOdonto`.`ProcedimentoOdonto` (`codigoProced`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcedimentoOdonto_has_Agendamento_Agendamento1`
    FOREIGN KEY (`Agendamento_idAgendamento`)
    REFERENCES `clinicaOdonto`.`Agendamento` (`idAgendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcedimentoOdonto_has_Agendamento_Paciente1`
    FOREIGN KEY (`Paciente_RG`)
    REFERENCES `clinicaOdonto`.`Paciente` (`RG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`Paciente_tem_seguroSaude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`Paciente_tem_seguroSaude` (
  `SeguroSaude_idSeguroSaude` INT NOT NULL,
  `Paciente_RG` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`SeguroSaude_idSeguroSaude`, `Paciente_RG`),
  INDEX `fk_Paciente_tem_seguroSaude_Paciente1_idx` (`Paciente_RG` ASC) VISIBLE,
  INDEX `fk_Paciente_tem_seguroSaude_SeguroSaude1_idx` (`SeguroSaude_idSeguroSaude` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_tem_seguroSaude_SeguroSaude1`
    FOREIGN KEY (`SeguroSaude_idSeguroSaude`)
    REFERENCES `clinicaOdonto`.`SeguroSaude` (`idSeguroSaude`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Paciente_tem_seguroSaude_Paciente1`
    FOREIGN KEY (`Paciente_RG`)
    REFERENCES `clinicaOdonto`.`Paciente` (`RG`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`RegistroClinico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`RegistroClinico` (
  `idRegistroClinico` INT AUTO_INCREMENT NOT NULL,
  `prescricao` VARCHAR(45) NULL,
  `recomendacao` VARCHAR(45) NOT NULL,
  `diagnostico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRegistroClinico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicaOdonto`.`RegistroClinicoPaciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicaOdonto`.`RegistroClinicoPaciente` (
  `Paciente_RG` VARCHAR(9) NOT NULL,
  `Dentista_Profissional_CPF` VARCHAR(15) NOT NULL,
  `RegistroClinico_idRegistroClinico` INT NOT NULL,
  PRIMARY KEY (`Paciente_RG`, `Dentista_Profissional_CPF`, `RegistroClinico_idRegistroClinico`),
  INDEX `fk_Paciente_has_Dentista_Dentista1_idx` (`Dentista_Profissional_CPF` ASC) VISIBLE,
  INDEX `fk_Paciente_has_Dentista_Paciente1_idx` (`Paciente_RG` ASC) VISIBLE,
  INDEX `fk_Paciente_has_Dentista_idRegistroClinico1_idx` (`RegistroClinico_idRegistroClinico` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_has_Dentista_Paciente1`
    FOREIGN KEY (`Paciente_RG`)
    REFERENCES `clinicaOdonto`.`Paciente` (`RG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Dentista_Dentista1`
    FOREIGN KEY (`Dentista_Profissional_CPF`)
    REFERENCES `clinicaOdonto`.`Dentista` (`Profissional_CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente_has_Dentista_idRegistroClinico1`
    FOREIGN KEY (`RegistroClinico_idRegistroClinico`)
    REFERENCES `clinicaOdonto`.`RegistroClinico` (`idRegistroClinico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
